### ISSUE TITLE
anchor keys sync blindly replaces the 1st program id in Anchor.toml, no matter the --provider.cluster

### ISSUE THREAD

**Issue by IaroslavMazur** [solana-foundation/anchor#3678]
There are 2 issues I've observed with `anchor keys sync`:

1) It blindly replaces the 1st "wrong" program id it can find in Anchor.toml, w/o taking into consideration the `--provider.cluster` argument it's being given &
2) It makes the same mistake, compounding its effect, when the command is executed repeatedly

e.g., given the following `Anchor.toml`:

```toml
[programs.devnet]
program_name = "1232wKNEUnTh8n5tCZHd55pbYCLy11xGg6Juu9zeysH5"

[programs.localnet]
program_name = "1232wKNEUnTh8n5tCZHd55pbYCLy11xGg6Juu9zeysH5"

[provider]
cluster = "localnet"
```

after the 1st execution of `anchor keys sync --provider.cluster "localnet" --provider.wallet "[path to a keypair file w/ an address/id != "1232wKNEUnTh8n5tCZHd55pbYCLy11xGg6Juu9zeysH5"]"`, the id inside `[programs.devnet]` is changed (even though the "localnet" cluster has been specified).

Additionally, if the very same command is being run a 2nd time, the id inside `[programs.localnet]` is changed, again - although, not because "localnet" made any difference here, but simply because it was, now, the 1st "wrong" program id in the file.
