### ISSUE TITLE
Build Fails: `Stack offset ... exceeded max offset` (`driftsort_main`) with Minimal Anchor Program (0.31.1)

### ISSUE THREAD

**Issue by rus-99-pk** [solana-foundation/anchor#3712]
Hello, Anchor Team,

I'm experiencing a consistent build failure with `anchor build` on a highly minimized Anchor program. The error indicates a stack offset problem related to `_ZN4core5slice4sort6stable14driftsort_main...`, even when the program module itself is effectively empty.

**Environment:**

*   **Anchor CLI Version:** `anchor-cli 0.31.1`
*   **Rust Version:** `rustc 1.87.0 (17067e9ac 2025-05-09)`
*   **Solana CLI Version:** `solana-cli 2.2.14`
*   **Node.js Version:** `v24.0.2`
*   **Operating System:** `macOS Sonoma`

**Problem Description:**

The `anchor build` command fails with the following error:

```
Compiling solana-system-interface v1.0.0
Compiling solana-stable-layout v2.2.1
Compiling solana-serialize-utils v2.2.1

Error: Function _ZN4core5slice4sort6stable14driftsort_main17h36537f13c5efa84eE Stack offset of 4104 exceeded max offset of 4096 by 8 bytes, please minimize large stack variables. Estimated function frame size: 4160 bytes. Exceeding the maximum stack offset may cause undefined behavior during execution.

Compiling solana-account-info v2.2.1
Compiling solana-bincode v2.2.1
Compiling solana-transaction-error v2.2.1
Compiling solana-epoch-schedule v2.2.1
```
*(The hash `h36537f13c5efa84eE` might vary slightly between builds).*

This error occurs even when all instructions and `#[derive(Accounts)]` structs are commented out from the program, leaving only basic data structure definitions and an empty `#[program]` module.

**Steps to Reproduce:**

1.  Set up an Anchor project with the following minimal configuration.
2.  Run `anchor build`.

**Minimal Reproducible Code:**

**`programs/gamefi_core/src/lib.rs`:**
```rust
use anchor_lang::prelude::*;

declare_id!("BBU...kF1p");

// Data structures
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Default, Debug)]
pub struct PendingClaimDetails {
    pub original_amount_to_claim: u64,
    pub amount_to_player_after_fee: u64,
    pub fee_to_treasury: u64,
    pub fee_to_burn: u64,
    pub preparation_timestamp: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Default, Debug)]
pub struct GlobalConfigInitParams {
    pub brch_token_mint_address: Pubkey,
    pub initial_server_key: Pubkey,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Default, Debug)]
pub struct P2EClaimUpdateParams {
    pub new_base_daily_claim_limit: u64,
}

#[account]
#[derive(Default, Debug)]
pub struct GlobalGameConfig {
    pub admin: Pubkey,
}

#[account]
#[derive(Default, Debug)]
pub struct PlayerGameData {
    pub user_wallet: Pubkey,
}

#[program]
pub mod gamefi_core {
    use super::*;
}

#[error_code]
pub enum ErrorCode {
    #[msg("Generic error for testing.")]
    GenericError,
}
```

**`programs/gamefi_core/Cargo.toml`:**
```toml
[package]
name = "gamefi_core"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gamefi_core"

[features]
no-entrypoint = []
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
```

**`Anchor.toml` (Workspace Root):**
```toml
[toolchain]
package_manager = "yarn"
# anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gamefi_core = "BBU...kF1p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
```

**`Cargo.toml` (Workspace Root):**
```toml
[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
```

**Troubleshooting Steps Taken:**

*   **Full Project Clean:** Executed `cargo clean` in both program and workspace directories, removed all `target` folders, deleted `node_modules` and lock files, then reinstalled Node.js dependencies.
*   **Code Minimization:**
    *   Commented out all program instructions (`pub fn` within `#[program]`).
    *   Commented out all `#[derive(Accounts)]` structs.
    *   Tried commenting out fields within remaining data structures (`PendingClaimDetails`, `GlobalGameConfig`, etc.) and even the structures themselves.
    *   Minimized `features` and `dependencies` in the program's `Cargo.toml`.
*   **Environment Check:** Confirmed that a fresh `anchor init new_project` compiles successfully on the same machine, indicating the general build environment is functional.
*   **Verbose Build:** Used `anchor build --verbose`, which shows the error occurring during the compilation of dependencies like `solana-system-interface`, etc., but doesn't pinpoint a specific part of *my* (now minimal) code.
*   **Anchor Version:** Ensured `anchor-lang` is 0.31.1.
*   **Build Profile:** Experimented with `opt-level = "z"` and `strip = "symbols"` in the workspace `Cargo.toml` for the release profile, but the error persists even when reverting to default Anchor release profile settings.

**Expected Behavior:**

A minimal Anchor program, particularly one with an empty `#[program]` module and only basic data structure definitions, should compile successfully without exceeding BPF stack limits.

**Actual Behavior:**

The build consistently fails with the "Stack offset ... exceeded max offset" error, referencing a Rust standard library sort function, even when there's no apparent user code that would trigger complex sorting or large stack allocations.

**Additional Context:**

This issue is a complete blocker. The fact that it occurs with such a stripped-down program suggests a potential problem in how Anchor or the BPF toolchain processes even minimal projects under certain (currently unknown) conditions, or perhaps an issue with how dependencies are compiled for the BPF target in this specific project setup.

Any assistance in diagnosing this further would be highly appreciated.
