### ISSUE TITLE
startup_wait or test validator cloning do not work as expected

### ISSUE THREAD

**Issue by hrls** [solana-foundation/anchor#3755]
I'm trying to setup a local validator to use SPL Token Program.

My `Anchor.toml` includes the following lines:
```toml
[test]
startup_wait = 10000 # 10 secs?

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
```

URL is just example, I'm using custom RPC provider actually.

In my tests, I'm trying to initialize the environment by create mint.
Nothing special, just `system_instruction::create_account_with_seed` and then `spl_token::instruction::initialize_mint2`, both in the same transaction.

Got the following error almost instantly:
```
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 1: Unsupported program id; 5 log messages:
  Program 11111111111111111111111111111111 invoke [1]
  Program 11111111111111111111111111111111 success
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
  Program is not deployed
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: Unsupported program id
```

However, the same test passes if I manually add a sleep in the test function. 10 secs is not enough, 15 secs is okay.

anchor-cli 0.31.1
solana-test-validator 2.2.16 (src:851b7526; feat:3073396398, client:Agave)
